---

- name: install tinc
  package: name=tinc state=latest

- name: create tinc systemd service file (redhat)
  template: >
    src=templates/tinc.service.j2
    dest=/etc/systemd/system/tinc.service
    owner=root
    group=root
    mode=0644

  notify: ["reload systemctl"]
  when: ansible_service_mgr == "systemd"

- name: create tinc unit file (generic)
  template: >
    src=templates/tinc@.service.j2
    dest=/etc/systemd/system/tinc@.service
    owner=root
    group=root
    mode=0644

  notify: ["reload systemctl"]
  when: ansible_service_mgr == "systemd"

- name: run handlers
  meta: flush_handlers

- name: ensure tinc netname directory exists
  file: >
    path=/etc/tinc/{{ netname }}/hosts
    recurse=True
    state=directory

- name: create /etc/tinc/nets.boot file from template
  template: >
    src=nets.boot.j2
    dest=/etc/tinc/nets.boot
    owner=root
    group=root
    mode=0644

  notify: ["restart tinc"]

- name: ensure tinc.conf contains connection to all other nodes
  template: >
    src=templates/tinc.conf.j2
    dest=/etc/tinc/{{ netname }}/tinc.conf
    owner=root
    group=root
    mode=0644

  notify: ["reload tinc"]

- name: create tinc-up file
  template: >
    src=tinc-up.j2
    dest=/etc/tinc/{{ netname }}/tinc-up
    owner=root
    group=root
    mode=0755

  notify: ["restart tinc"]

- name: create tinc-down file
  template: >
    src=tinc-down.j2
    dest=/etc/tinc/{{ netname }}/tinc-down
    owner=root
    group=root
    mode=0755

  notify: ["restart tinc"]

- name: ensure tinc hosts file binds to physical ip address
  lineinfile: >
    dest=/etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
    line="Address = {{ physical_ip }}"
    create=yes

  notify: ["restart tinc"]

- name: ensure subnet ip address is properly set in tinc host file
  lineinfile: >
    dest=/etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
    line="Subnet = {{ vpn_ip }}/{{ vpn_subnet_cidr_netmask }}"
    create=yes

  notify: ["restart tinc"]

- name: check whether /etc/tinc/netname/hosts/ansible_hostname contains "-----END RSA PUBLIC KEY-----"
  command: awk '/^-----END RSA PUBLIC KEY-----$/'  /etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
  changed_when: "public_key.stdout != '-----END RSA PUBLIC KEY-----'"
  register: public_key

# this is necessary because the public key will not be generated (non-interactively) if the private key already exists
- name: delete private key and regenerate keypair if public key is absent from tinc hosts file
  file: >
    path=/etc/tinc/{{ netname }}/rsa_key.priv
    state=absent
  when: public_key.changed

- name: create tinc private key (and append public key to tincd hosts file)
  shell: tincd -n {{ netname }} -K4096 creates=/etc/tinc/{{ netname }}/rsa_key.priv

  notify: ["restart tinc"]

- name: fetch tinc hosts file after key creation
  fetch: >
    src=/etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
    dest=fetch/{{ ansible_hostname }}
    flat=yes

  notify: ["reload tinc"]

- name: sync the fetched tinc hosts files on each host
  synchronize: >
    src=fetch/
    dest=/etc/tinc/{{ netname }}/hosts/

  notify: ["reload tinc"]

- name: ensure tinc is started
  service: >
    name=tinc
    enabled=yes
    state=started
    pattern=tincd -n {{ netname }}

- name: add nodes to /etc/hosts (ansible_inventory resolves to vpn_ip)
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].vpn_ip }} {{item}}" state=present
  when: hostvars[item].vpn_ip is defined
  with_items: "{{ play_hosts }}"
